class CustomData {
  String? name;
  String? courseName;

  CustomData({
    this.name,
    this.courseName,
  });
}

class SecondarySchoolData {
  static const List<String> learningFeatures = [
    'AI Tutoring',
    'Live Classes',
    'Exam Practice',
    'Project Labs',
    'Research Skills',
    'Mentor Support',
    'Progress Tracker',
    'Digital Library',
    'Homework Review',
    'Study Planner',
    'Skill Badges',
    'Parent Insights',
    'Career Roadmaps',
    'Revision Packs',
    'Quiz Challenges',
    'Peer Groups',
    'Group Projects',
    'Video Lessons',
    'Flash Revision',
    'Practical Labs',
    'Weekly Feedback',
    'Mock Exams',
    'STEM Clubs',
    'Language Labs',
    'Essay Coaching',
    'Adaptive Learning',
    'Focus Timer',
    'Class Notes',
    'Attendance Tracking',
    'Scholarship Tips',
    'Interview Prep',
    'Classroom Simulations',
    'Portfolio Builder',
    'Case Studies',
    'Micro Lessons',
    'Mission Tasks',
    'Learning Paths',
    'Career Discovery',
    'Back-to-School Plans',
    'Peer Mentoring',
    'Teacher Dashboards',
    'Question Bank',
    'Remedial Support',
    'Stretch Challenges',
    'Skill Matrix',
    'Confidence Builder',
    'Concept Maps',
    'Presentation Studio',
    'Reading Clubs',
    'Writing Workshop',
    'Coding Arcade',
    'Science Fair',
    'Art Studio',
    'Music Lab',
    'Leadership Track',
    'Community Projects',
    'Learning Analytics',
    'Goal Tracking',
    'Scholar Support',
    'Career Explorer',
    'Creative Thinking',
    'Critical Thinking',
    'Digital Citizenship',
    'Entrepreneurship',
    'Sustainability',
    'Campus Readiness',
    'Olympiad Prep',
    'School Clubs',
    'Reflection Journal',
  ];

  static const List<Map<String, String>> subjectCatalog = [
    {'name': 'Mathematics', 'description': 'Algebra, Geometry & Problem Solving'},
    {'name': 'English Language', 'description': 'Grammar, Reading & Comprehension'},
    {'name': 'Biology', 'description': 'Genetics, Cells & Living Systems'},
    {'name': 'Chemistry', 'description': 'Atoms, Reactions & Experiments'},
    {'name': 'Physics', 'description': 'Motion, Energy & Scientific Inquiry'},
    {'name': 'ICT', 'description': 'Digital Skills, Coding & Networking'},
    {'name': 'Economics', 'description': 'Markets, Trade & Decision Making'},
    {'name': 'Accounting', 'description': 'Records, Budgets & Finance'},
    {'name': 'Geography', 'description': 'Maps, Climate & Human Systems'},
    {'name': 'History', 'description': 'Civilisations, Governance & Legacy'},
    {'name': 'Civic Education', 'description': 'Citizenship, Rights & Society'},
    {'name': 'Literature', 'description': 'Poetry, Drama & Analysis'},
    {'name': 'French', 'description': 'Speaking, Listening & Writing'},
    {'name': 'Spanish', 'description': 'Conversation & Comprehension'},
    {'name': 'Arabic', 'description': 'Language, Culture & Expression'},
    {'name': 'Government', 'description': 'Political Systems & Leadership'},
    {'name': 'Agricultural Science', 'description': 'Plants, Soil & Farm Systems'},
    {'name': 'Home Economics', 'description': 'Nutrition, Family & Design'},
    {'name': 'Computer Science', 'description': 'Programming & Logical Thinking'},
    {'name': 'Business Studies', 'description': 'Enterprise, Management & Market'},
    {'name': 'Art', 'description': 'Creativity, Design & Visual Storytelling'},
    {'name': 'Music', 'description': 'Rhythm, Theory & Performance'},
    {'name': 'Physical Education', 'description': 'Fitness, Sport & Wellbeing'},
    {'name': 'Religious Studies', 'description': 'Ethics, Belief & Culture'},
    {'name': 'Psychology', 'description': 'Behaviour, Mind & Learning'},
    {'name': 'Environmental Science', 'description': 'Earth, Ecology & Sustainability'},
    {'name': 'Further Mathematics', 'description': 'Advanced Reasoning & Calculus'},
    {'name': 'Statistics', 'description': 'Data Interpretation & Analysis'},
    {'name': 'Mechanics', 'description': 'Forces, Motion & Machines'},
    {'name': 'Electronics', 'description': 'Circuits, Devices & Systems'},
    {'name': 'Technical Drawing', 'description': 'Design, Drafting & Precision'},
    {'name': 'Food & Nutrition', 'description': 'Meal Planning & Healthy Living'},
    {'name': 'Health Education', 'description': 'Lifestyle, Safety & Wellness'},
    {'name': 'Drama', 'description': 'Performance, Expression & Theatre'},
    {'name': 'Communication Skills', 'description': 'Presentation & Public Speaking'},
    {'name': 'Research Methods', 'description': 'Study Design & Evidence Review'},
    {'name': 'Earth Science', 'description': 'Rocks, Weather & Planetary Systems'},
    {'name': 'Biotechnology', 'description': 'Life Sciences & Applied Innovation'},
    {'name': 'Astronomy', 'description': 'Stars, Planets & Space Exploration'},
    {'name': 'Marine Science', 'description': 'Oceans, Ecosystems & Research'},
    {'name': 'Creative Writing', 'description': 'Narrative, Style & Publishing'},
    {'name': 'Entrepreneurship', 'description': 'Ideas, Products & Business Growth'},
    {'name': 'Media Studies', 'description': 'Digital Communication & Content'},
    {'name': 'Photography', 'description': 'Composition, Editing & Visuals'},
    {'name': 'Robotics', 'description': 'Automation, Sensors & Engineering'},
    {'name': 'Engineering', 'description': 'Design, Systems & Materials'},
    {'name': 'Logic', 'description': 'Reasoning, Proof & Critical Analysis'},
    {'name': 'Finance', 'description': 'Money Management & Investments'},
    {'name': 'Marketing', 'description': 'Branding, Advertising & Strategy'},
    {'name': 'Sociology', 'description': 'Culture, Society & Behaviour'},
    {'name': 'Criminology', 'description': 'Law, Justice & Social Systems'},
    {'name': 'Philosophy', 'description': 'Ethics, Inquiry & Meaning'},
    {'name': 'Public Administration', 'description': 'Policy, Governance & Delivery'},
    {'name': 'Legal Studies', 'description': 'Law, Rights & Justice'},
    {'name': 'Tourism', 'description': 'Hospitality, Travel & Service'},
    {'name': 'Hospitality', 'description': 'Customer Care & Service Skills'},
    {'name': 'Fashion Design', 'description': 'Style, Sewing & Trend Creation'},
    {'name': 'Graphic Design', 'description': 'Visual Identity & Digital Creation'},
    {'name': 'Web Development', 'description': 'Sites, Apps & Interactive Design'},
    {'name': 'Mobile App Design', 'description': 'UX, Interface & Prototyping'},
    {'name': 'Data Science', 'description': 'Analysis, Modelling & Insight'},
    {'name': 'Cybersecurity', 'description': 'Online Safety & Digital Protection'},
    {'name': 'Animation', 'description': 'Motion, Storyboards & VFX'},
    {'name': 'Film Studies', 'description': 'Production, Critique & Storytelling'},
    {'name': 'Robotics Club', 'description': 'Hands-on Stem Challenges'},
    {'name': 'Debate', 'description': 'Argument, Speech & Persuasion'},
    {'name': 'Leadership', 'description': 'Influence, Teamwork & Growth'},
    {'name': 'Wellbeing', 'description': 'Mental Health & Resilience'},
    {'name': 'Career Planning', 'description': 'Goals, Skills & Future Pathways'},
    {'name': 'Research Skills', 'description': 'Investigation, Evidence & Discovery'},
    {'name': 'Global Studies', 'description': 'World Issues, Culture & Diplomacy'},
    {'name': 'Innovation Lab', 'description': 'Design Thinking & Real-world Ideas'},
    {'name': 'STEM Foundation', 'description': 'Core Science, Maths & Problem Solving'},
    {'name': 'Project Based Learning', 'description': 'Applied, Real-world School Tasks'},
  ];
}
